/* -*- sv -*- File generated by the BNF Converter (bnfc 2.9.7). */

/*******************************************************/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

`include "C/CInterpBase.svh"


task InterpBase::visitProgram(Program p); endtask //abstract class
task InterpBase::visitStmt_Item(Stmt_Item p); endtask //abstract class
task InterpBase::visitVar_Assignment(Var_Assignment p); endtask //abstract class
task InterpBase::visitJump_Stmt(Jump_Stmt p); endtask //abstract class
task InterpBase::visitFuncOrProcCall(FuncOrProcCall p); endtask //abstract class
task InterpBase::visitBuiltin_Task(Builtin_Task p); endtask //abstract class
task InterpBase::visitBuiltin_Fn(Builtin_Fn p); endtask //abstract class
task InterpBase::visitPrint_Arg(Print_Arg p); endtask //abstract class
task InterpBase::visitProc_Definition(Proc_Definition p); endtask //abstract class
task InterpBase::visitFunc_Definition(Func_Definition p); endtask //abstract class
task InterpBase::visitDefinition(Definition p); endtask //abstract class
task InterpBase::visitFormal_Arg(Formal_Arg p); endtask //abstract class
task InterpBase::visitElse_If(Else_If p); endtask //abstract class
task InterpBase::visitElse_Opt(Else_Opt p); endtask //abstract class
task InterpBase::visitConditional_Stmt(Conditional_Stmt p); endtask //abstract class
task InterpBase::visitLoop_Stmt(Loop_Stmt p); endtask //abstract class
task InterpBase::visitFor_Init_Opt(For_Init_Opt p); endtask //abstract class
task InterpBase::visitExpr_Opt(Expr_Opt p); endtask //abstract class
task InterpBase::visitFor_Step_Opt(For_Step_Opt p); endtask //abstract class
task InterpBase::visitOp(Op p); endtask //abstract class
task InterpBase::visitExpr(Expr p); endtask //abstract class
task InterpBase::visitPrimary(Primary p); endtask //abstract class
task InterpBase::visitRange_Expr_Opt(Range_Expr_Opt p); endtask //abstract class
task InterpBase::visitRange_Expr(Range_Expr p); endtask //abstract class
task InterpBase::visitUnary_Operator(Unary_Operator p); endtask //abstract class
task InterpBase::visitInc_Or_Dec_Operator(Inc_Or_Dec_Operator p); endtask //abstract class
task InterpBase::visitNumber(Number p); endtask //abstract class
task InterpBase::visitString_Literal(String_Literal p); endtask //abstract class

task InterpBase::visitProgram1(Program1 p);
  /* Code For Program1 Goes Here */

  p.liststmt_item_.accept(this);

endtask

task InterpBase::visitVarDeclStmt(VarDeclStmt p);
  /* Code For VarDeclStmt Goes Here */

  visitIdent(p.ident_);

endtask

task InterpBase::visitVarAssDeclStmt(VarAssDeclStmt p);
  /* Code For VarAssDeclStmt Goes Here */

  p.var_assignment_.accept(this);

endtask

task InterpBase::visitAssignmentStmt(AssignmentStmt p);
  /* Code For AssignmentStmt Goes Here */

  p.var_assignment_.accept(this);

endtask

task InterpBase::visitConditionalStmt(ConditionalStmt p);
  /* Code For ConditionalStmt Goes Here */

  p.conditional_stmt_.accept(this);

endtask

task InterpBase::visitIncDecOpStmt(IncDecOpStmt p);
  /* Code For IncDecOpStmt Goes Here */

  visitIdent(p.ident_);
  p.inc_or_dec_operator_.accept(this);

endtask

task InterpBase::visitLoopStmt(LoopStmt p);
  /* Code For LoopStmt Goes Here */

  p.loop_stmt_.accept(this);

endtask

task InterpBase::visitJumpStmt(JumpStmt p);
  /* Code For JumpStmt Goes Here */

  p.jump_stmt_.accept(this);

endtask

task InterpBase::visitBlockStmt(BlockStmt p);
  /* Code For BlockStmt Goes Here */

  p.liststmt_item_.accept(this);

endtask

task InterpBase::visitBuiltInStmt(BuiltInStmt p);
  /* Code For BuiltInStmt Goes Here */

  p.builtin_task_.accept(this);

endtask

task InterpBase::visitProcDefStmt(ProcDefStmt p);
  /* Code For ProcDefStmt Goes Here */

  p.proc_definition_.accept(this);

endtask

task InterpBase::visitFuncDefStmt(FuncDefStmt p);
  /* Code For FuncDefStmt Goes Here */

  p.func_definition_.accept(this);

endtask

task InterpBase::visitProcCallStmt(ProcCallStmt p);
  /* Code For ProcCallStmt Goes Here */

  p.funcorproccall_.accept(this);

endtask

task InterpBase::visitAssignment(Assignment p);
  /* Code For Assignment Goes Here */

  visitIdent(p.ident_);
  p.range_expr_opt_.accept(this);
  p.expr_.accept(this);

endtask

task InterpBase::visitBreak(Break p);
  /* Code For Break Goes Here */


endtask

task InterpBase::visitContinue(Continue p);
  /* Code For Continue Goes Here */


endtask

task InterpBase::visitReturn(Return p);
  /* Code For Return Goes Here */

  p.expr_opt_.accept(this);

endtask

task InterpBase::visitCall(Call p);
  /* Code For Call Goes Here */

  visitIdent(p.ident_);
  p.listexpr_.accept(this);

endtask

task InterpBase::visitPrint(Print p);
  /* Code For Print Goes Here */

  p.listprint_arg_.accept(this);

endtask

task InterpBase::visitRegWr(RegWr p);
  /* Code For RegWr Goes Here */

  p.expr_1.accept(this);
  p.expr_2.accept(this);

endtask

task InterpBase::visitWait(Wait p);
  /* Code For Wait Goes Here */

  p.expr_.accept(this);

endtask

task InterpBase::visitFatal(Fatal p);
  /* Code For Fatal Goes Here */

  p.expr_.accept(this);

endtask

task InterpBase::visitRegRd(RegRd p);
  /* Code For RegRd Goes Here */

  p.expr_.accept(this);

endtask

task InterpBase::visitCeil(Ceil p);
  /* Code For Ceil Goes Here */

  p.expr_.accept(this);

endtask

task InterpBase::visitFloor(Floor p);
  /* Code For Floor Goes Here */

  p.expr_.accept(this);

endtask

task InterpBase::visitLog2(Log2 p);
  /* Code For Log2 Goes Here */

  p.expr_.accept(this);

endtask

task InterpBase::visitSys(Sys p);
  /* Code For Sys Goes Here */

  p.string_literal_.accept(this);

endtask

task InterpBase::visitIsDefd(IsDefd p);
  /* Code For IsDefd Goes Here */

  visitIdent(p.ident_);

endtask

task InterpBase::visitPrExpr(PrExpr p);
  /* Code For PrExpr Goes Here */

  p.expr_.accept(this);

endtask

task InterpBase::visitPrString(PrString p);
  /* Code For PrString Goes Here */

  p.string_literal_.accept(this);

endtask

task InterpBase::visitPrHex(PrHex p);
  /* Code For PrHex Goes Here */

  p.expr_.accept(this);

endtask

task InterpBase::visitPrBin(PrBin p);
  /* Code For PrBin Goes Here */

  p.expr_.accept(this);

endtask

task InterpBase::visitProcDef(ProcDef p);
  /* Code For ProcDef Goes Here */

  p.definition_.accept(this);

endtask

task InterpBase::visitFuncDef(FuncDef p);
  /* Code For FuncDef Goes Here */

  p.definition_.accept(this);

endtask

task InterpBase::visitDefn(Defn p);
  /* Code For Defn Goes Here */

  visitIdent(p.ident_);
  p.listformal_arg_.accept(this);
  p.stmt_item_.accept(this);

endtask

task InterpBase::visitFormal(Formal p);
  /* Code For Formal Goes Here */

  visitIdent(p.ident_);

endtask

task InterpBase::visitElsIf(ElsIf p);
  /* Code For ElsIf Goes Here */

  p.expr_.accept(this);
  p.stmt_item_.accept(this);

endtask

task InterpBase::visitElseIsEmpty(ElseIsEmpty p);
  /* Code For ElseIsEmpty Goes Here */


endtask

task InterpBase::visitElseIsElse(ElseIsElse p);
  /* Code For ElseIsElse Goes Here */

  p.stmt_item_.accept(this);

endtask

task InterpBase::visitIf(If p);
  /* Code For If Goes Here */

  p.expr_.accept(this);
  p.stmt_item_.accept(this);
  p.listelse_if_.accept(this);
  p.else_opt_.accept(this);

endtask

task InterpBase::visitWhile(While p);
  /* Code For While Goes Here */

  p.expr_.accept(this);
  p.stmt_item_.accept(this);

endtask

task InterpBase::visitFor(For p);
  /* Code For For Goes Here */

  p.for_init_opt_.accept(this);
  p.expr_opt_.accept(this);
  p.for_step_opt_.accept(this);
  p.stmt_item_.accept(this);

endtask

task InterpBase::visitForInitIsEmpty(ForInitIsEmpty p);
  /* Code For ForInitIsEmpty Goes Here */


endtask

task InterpBase::visitForInitIsInit(ForInitIsInit p);
  /* Code For ForInitIsInit Goes Here */

  p.var_assignment_.accept(this);

endtask

task InterpBase::visitForInitIsVarInit(ForInitIsVarInit p);
  /* Code For ForInitIsVarInit Goes Here */

  p.var_assignment_.accept(this);

endtask

task InterpBase::visitExprIsEmpty(ExprIsEmpty p);
  /* Code For ExprIsEmpty Goes Here */


endtask

task InterpBase::visitExprIsExpr(ExprIsExpr p);
  /* Code For ExprIsExpr Goes Here */

  p.expr_.accept(this);

endtask

task InterpBase::visitForStepIsEmpty(ForStepIsEmpty p);
  /* Code For ForStepIsEmpty Goes Here */


endtask

task InterpBase::visitForStepIsAssignment(ForStepIsAssignment p);
  /* Code For ForStepIsAssignment Goes Here */

  p.var_assignment_.accept(this);

endtask

task InterpBase::visitForStepIsIncOrDec(ForStepIsIncOrDec p);
  /* Code For ForStepIsIncOrDec Goes Here */

  visitIdent(p.ident_);
  p.inc_or_dec_operator_.accept(this);

endtask

task InterpBase::visitPow(Pow p);
  /* Code For Pow Goes Here */


endtask

task InterpBase::visitMul(Mul p);
  /* Code For Mul Goes Here */


endtask

task InterpBase::visitDiv(Div p);
  /* Code For Div Goes Here */


endtask

task InterpBase::visitMod(Mod p);
  /* Code For Mod Goes Here */


endtask

task InterpBase::visitAdd(Add p);
  /* Code For Add Goes Here */


endtask

task InterpBase::visitSub(Sub p);
  /* Code For Sub Goes Here */


endtask

task InterpBase::visitLAnd(LAnd p);
  /* Code For LAnd Goes Here */


endtask

task InterpBase::visitXor(Xor p);
  /* Code For Xor Goes Here */


endtask

task InterpBase::visitLOr(LOr p);
  /* Code For LOr Goes Here */


endtask

task InterpBase::visitRsh(Rsh p);
  /* Code For Rsh Goes Here */


endtask

task InterpBase::visitLsh(Lsh p);
  /* Code For Lsh Goes Here */


endtask

task InterpBase::visitLt(Lt p);
  /* Code For Lt Goes Here */


endtask

task InterpBase::visitLeq(Leq p);
  /* Code For Leq Goes Here */


endtask

task InterpBase::visitGt(Gt p);
  /* Code For Gt Goes Here */


endtask

task InterpBase::visitGeq(Geq p);
  /* Code For Geq Goes Here */


endtask

task InterpBase::visitEq(Eq p);
  /* Code For Eq Goes Here */


endtask

task InterpBase::visitNeq(Neq p);
  /* Code For Neq Goes Here */


endtask

task InterpBase::visitAnd(And p);
  /* Code For And Goes Here */


endtask

task InterpBase::visitOr(Or p);
  /* Code For Or Goes Here */


endtask

task InterpBase::visitExprPrim(ExprPrim p);
  /* Code For ExprPrim Goes Here */

  p.primary_.accept(this);

endtask

task InterpBase::visitExprUnary(ExprUnary p);
  /* Code For ExprUnary Goes Here */

  p.unary_operator_.accept(this);
  p.expr_.accept(this);

endtask

task InterpBase::visitExprBltin(ExprBltin p);
  /* Code For ExprBltin Goes Here */

  p.builtin_fn_.accept(this);

endtask

task InterpBase::visitExprFuncCall(ExprFuncCall p);
  /* Code For ExprFuncCall Goes Here */

  p.funcorproccall_.accept(this);

endtask

task InterpBase::visitExprTernary(ExprTernary p);
  /* Code For ExprTernary Goes Here */

  p.expr_1.accept(this);
  p.expr_2.accept(this);
  p.expr_3.accept(this);

endtask

task InterpBase::visitEOp(EOp p);
  /* Code For EOp Goes Here */

  p.expr_1.accept(this);
  p.op_.accept(this);
  p.expr_2.accept(this);

endtask

task InterpBase::visitPrimIdent(PrimIdent p);
  /* Code For PrimIdent Goes Here */

  visitIdent(p.ident_);
  p.range_expr_opt_.accept(this);

endtask

task InterpBase::visitPrimNumber(PrimNumber p);
  /* Code For PrimNumber Goes Here */

  p.number_.accept(this);

endtask

task InterpBase::visitRangeExprIsEmpty(RangeExprIsEmpty p);
  /* Code For RangeExprIsEmpty Goes Here */


endtask

task InterpBase::visitRangeExprIsRange(RangeExprIsRange p);
  /* Code For RangeExprIsRange Goes Here */

  p.range_expr_.accept(this);

endtask

task InterpBase::visitRangeExprBit(RangeExprBit p);
  /* Code For RangeExprBit Goes Here */

  p.expr_.accept(this);

endtask

task InterpBase::visitRangeExprRange(RangeExprRange p);
  /* Code For RangeExprRange Goes Here */

  p.expr_1.accept(this);
  p.expr_2.accept(this);

endtask

task InterpBase::visitUnaryPlus(UnaryPlus p);
  /* Code For UnaryPlus Goes Here */


endtask

task InterpBase::visitUnaryMinus(UnaryMinus p);
  /* Code For UnaryMinus Goes Here */


endtask

task InterpBase::visitUnaryNot(UnaryNot p);
  /* Code For UnaryNot Goes Here */


endtask

task InterpBase::visitUnaryComp(UnaryComp p);
  /* Code For UnaryComp Goes Here */


endtask

task InterpBase::visitIncr(Incr p);
  /* Code For Incr Goes Here */


endtask

task InterpBase::visitDecr(Decr p);
  /* Code For Decr Goes Here */


endtask

task InterpBase::visitDecimal(Decimal p);
  /* Code For Decimal Goes Here */

  visitDecimal_Number(p.decimal_number_);

endtask

task InterpBase::visitBinary(Binary p);
  /* Code For Binary Goes Here */

  visitBinaryNumber(p.binarynumber_);

endtask

task InterpBase::visitHex(Hex p);
  /* Code For Hex Goes Here */

  visitHexNumber(p.hexnumber_);

endtask

task InterpBase::visitReal(Real p);
  /* Code For Real Goes Here */

  visitReal_Number(p.real_number_);

endtask

task InterpBase::visitStringLit(StringLit p);
  /* Code For StringLit Goes Here */

  visitAnyChars(p.anychars_);

endtask


task InterpBase::visitListStmt_Item(ListStmt_Item  liststmt_item);
  for ( int i = 0; i < liststmt_item.v.size() ; i++)
  begin
    liststmt_item.v[i].accept(this);
  end
endtask

task InterpBase::visitListExpr(ListExpr  listexpr);
  for ( int i = 0; i < listexpr.v.size() ; i++)
  begin
    listexpr.v[i].accept(this);
  end
endtask

task InterpBase::visitListPrint_Arg(ListPrint_Arg  listprint_arg);
  for ( int i = 0; i < listprint_arg.v.size() ; i++)
  begin
    listprint_arg.v[i].accept(this);
  end
endtask

task InterpBase::visitListFormal_Arg(ListFormal_Arg  listformal_arg);
  for ( int i = 0; i < listformal_arg.v.size() ; i++)
  begin
    listformal_arg.v[i].accept(this);
  end
endtask

task InterpBase::visitListElse_If(ListElse_If  listelse_if);
  for ( int i = 0; i < listelse_if.v.size() ; i++)
  begin
    listelse_if.v[i].accept(this);
  end
endtask


task InterpBase::visitDecimal_Number(Decimal_Number x);
  /* Code for Decimal_Number Goes Here */
endtask

task InterpBase::visitReal_Number(Real_Number x);
  /* Code for Real_Number Goes Here */
endtask

task InterpBase::visitBinaryNumber(BinaryNumber x);
  /* Code for BinaryNumber Goes Here */
endtask

task InterpBase::visitHexNumber(HexNumber x);
  /* Code for HexNumber Goes Here */
endtask

task InterpBase::visitAnyChars(AnyChars x);
  /* Code for AnyChars Goes Here */
endtask

task InterpBase::visitInteger(Integer x);
  /* Code for Integer Goes Here */
endtask

task InterpBase::visitChar(Char x);
  /* Code for Char Goes Here */
endtask

task InterpBase::visitDouble(Double x);
  /* Code for Double Goes Here */
endtask

task InterpBase::visitString(String x);
  /* Code for String Goes Here */
endtask

task InterpBase::visitIdent(Ident x);
  /* Code for Ident Goes Here */
endtask



